import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./theme-config.css";

import { Card, Theme } from "@radix-ui/themes";
import { getServerSession } from "next-auth";
import NavBar from "./NavBar";
import SideBar from "./SideBar";
import { authOptions } from "@/app/api/auth/authOptions";
import Login from "./components/Login";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.variable}>
        <main>
          <Theme accentColor="blue" grayColor="slate">
            <div className="flex justify-between bg-slate-100">
              {session ? <SideBar /> : <></>}
              <div className="w-full h-full">
                <div className="flex flex-col h-full p-5">
                  {session ? (
                    <NavBar name={session.user?.name ?? "Guest"} />
                  ) : (
                    <></>
                  )}
                  {session ? (
                    <Card className="min-h-[40rem]">{children}</Card>
                  ) : (
                    <Login />
                  )}
                </div>
              </div>
            </div>
          </Theme>
        </main>
      </body>
    </html>
  );
}
