import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Theme, Card } from "@radix-ui/themes";
import SideBar from "./SideBar";
import NavBar from "./NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <main>
          <Theme accentColor="blue" grayColor="slate">
            <div className="flex justify-between bg-slate-100">
              <SideBar />
              <div className="w-full h-full">
                <div className="flex flex-col h-full p-5">
                  <NavBar />
                  <Card className="min-h-[40rem]">{children}</Card>
                </div>
              </div>
            </div>
          </Theme>
        </main>
      </body>
    </html>
  );
}
